### ISSUE TITLE
<KeyPress>が２つあるとバグるよね

### ISSUE THREAD

**Issue by c0a21088** [c0a2110056/ProjExD#12]
https://github.com/c0a2110056/ProjExD/blob/a99c099fbef2b373485d6539285636e4311ff833/ex03/maze.py#L89
自分もバグでました。自分はここの<KeyPress>が上書き？じゃないけどなんか良く分からないけどバグりますよね、頑張って実装してみてください！

**Comment by c0a2110056** [comment]
ご指摘ありがとうございます。Keyに変えてみました
