### ISSUE TITLE
ここは何をしているのでしょうか？

### ISSUE THREAD

**Issue by c0a21088** [c0a2110056/ProjExD#15]
https://github.com/c0a2110056/ProjExD/blob/d9506f9fa80e16473274c49c8c1febf520dde4e5/ex04/dodge_bomb.py#L73
ここの処理はtry構文を使っていますが、どのようなエラーが出ているのでしょうか？
ここの一文で起こる全てのエラーが例外処理されるため、出来ればエラーの名前でtryするべきだと思います

**Comment by c0a2110056** [comment]
爆弾を新しく作る際に、localとなる変数が出てきてしまうのでlocal~と出てしまいます。時間の関係上、すべてのエラーを例外処理してしまいましたが、おっしゃる通りだと思います。ご助言ありがとうございます。

**Comment by c0a2110056** [comment]
変えてみました。
