### ISSUE TITLE
変数名

### ISSUE THREAD

**Issue by c0a2111229** [c0a2110056/ProjExD#2]
https://github.com/c0a2110056/ProjExD/blob/ff0805e4ab49f7c3c963d8f8d389208628a32600/ex01/quiz.py#L4
変数名わかりやすくていいね！！

**Comment by c0a2110056** [comment]
kotaeを英語圏にもわかりやすくanswerとしてみました。あと、普通にランダムの範囲が間違っていて、気づくきっかけになりました。ありがとうございました。
