### ISSUE TITLE
魔神のおことば

### ISSUE THREAD

**Issue by c0a21124f8** [c0a2110056/ProjExD#4]
https://github.com/c0a2110056/ProjExD/blob/9a88ed1a9f0f55378fee5b6a2522e12846687676/ex01/alphabet.py#L29
( A or B )and (B or A)のようにまとめればわざわざifを重ねなくてもいいと思うZO！！！

**Comment by c0a2110056** [comment]
一回ずつ文字の正誤判定を行った後に、正しければその次の処理に行くようなプログラムを考えていたので、確かに一気に判定するならそうすべきだと思いました。ありがたいおことばありがとうございました。
